export const users = [
    {
        userId: "u001",
        name: "Ethan Walker",
        email: "ethan.walker@example.com",
        avatar: "https://randomuser.me/api/portraits/men/32.jpg",
        status: "online",
        lastActive: "09:25 AM",
    },
    {
        userId: "u002",
        name: "Olivia Johnson",
        email: "olivia.johnson@example.com",
        avatar: "https://randomuser.me/api/portraits/women/44.jpg",
        status: "away",
        lastActive: "09:18 AM",
    },
    {
        userId: "u003",
        name: "Liam Anderson",
        email: "liam.anderson@example.com",
        avatar: "https://randomuser.me/api/portraits/men/41.jpg",
        status: "offline",
        lastActive: "08:50 AM",
    },
    {
        userId: "u004",
        name: "Ava Thompson",
        email: "ava.thompson@example.com",
        avatar: "https://randomuser.me/api/portraits/women/68.jpg",
        status: "online",
        lastActive: "09:22 AM",
    },
    {
        userId: "u005",
        name: "Noah Harris",
        email: "noah.harris@example.com",
        avatar: "https://randomuser.me/api/portraits/men/53.jpg",
        status: "offline",
        lastActive: "09:00 AM",
    },
    {
        userId: "u006",
        name: "Sophia Martinez",
        email: "sophia.martinez@example.com",
        avatar: "https://randomuser.me/api/portraits/women/36.jpg",
        status: "away",
        lastActive: "09:15 AM",
    },
    {
        userId: "u007",
        name: "James Carter",
        email: "james.carter@example.com",
        avatar: "https://randomuser.me/api/portraits/men/27.jpg",
        status: "online",
        lastActive: "09:26 AM",
    },
    {
        userId: "u008",
        name: "Isabella Lewis",
        email: "isabella.lewis@example.com",
        avatar: "https://randomuser.me/api/portraits/women/22.jpg",
        status: "online",
        lastActive: "09:25 AM",
    },
    {
        userId: "u009",
        name: "Mason Clark",
        email: "mason.clark@example.com",
        avatar: "https://randomuser.me/api/portraits/men/45.jpg",
        status: "away",
        lastActive: "09:10 AM",
    },
    {
        userId: "u010",
        name: "Emma Wilson",
        email: "emma.wilson@example.com",
        avatar: "https://randomuser.me/api/portraits/women/11.jpg",
        status: "online",
        lastActive: "09:24 AM",
    },
];
