export const randomReplies = [
    "That's interesting! Tell me more.",
    "I see what you mean.",
    "Absolutely! I agree with you.",
    "That sounds great!",
    "Really? That's amazing!",
    "I understand your point.",
    "Thanks for sharing that!",
    "Cool! I hadn't thought of it that way.",
    "You're absolutely right!",
    "That makes perfect sense.",
    "Wow, that's incredible!",
    "I appreciate you telling me that.",
    "That's a good point!",
    "Interesting perspective!",
    "I'm glad you shared that with me.",
    "That's really helpful, thanks!",
    "I can see why you'd think that.",
    "That's pretty awesome!",
    "Good to know!",
    "Thanks for the info!",
];
